Feature/forget password
PAWII-Portal-Loker/backend pull request #34
Opened 2024-12-29 13:52 UTC by Rendy752

Reset token expiration time 5 minute

2024-12-29 14:38 UTC, fanesz commented
create separated branch from this branch #33

2024-12-29 16:56 UTC, fanesz requested changes
Harusnyo sih ikutin kayak uvce, ado pengecekan di middleware untuk jwt reset pass. tapi dak usalah, low priority ini

2024-12-29 16:56 UTC, fanesz commented on src/modules/auth/controllers/auth.controller.ts
> +        }
```suggestion
        const user = await this.userSubservice.findOne({ _id: userId });
        if (!user) {
          return this.handleError(res, {
            statusCode: StatusNotFound,
            message: "User not found",
          });
        }
```

2024-12-29 16:56 UTC, fanesz commented on src/modules/auth/controllers/auth.controller.ts
> +        }
no extra space to tell that this if check is error handling from previous line action

2024-12-29 16:56 UTC, fanesz commented on src/modules/auth/controllers/auth.controller.ts
> +        }
```suggestion
        const updatedUser = await this.userSubservice.update(
          { _id: userId },
          { password: hashedPassword },
        );
        if (this.isServiceError(res, updatedUser)) {
          return;
        }
```

2024-12-29 16:56 UTC, fanesz commented on src/modules/auth/controllers/auth.controller.ts
> +        await this.redisClient.del(`forget-password:${resetToken}`);
```suggestion
        this.redisClient.del(`forget-password:${resetToken}`);
```
doesn't need to be await

2024-12-30 10:35 UTC, Rendy752 commented
okay

2024-12-30 10:39 UTC, fanesz approved these changes

2024-12-30 10:39 UTC, merged